// =============================================================================
// FigForge — UI Toolkit backend. Turns a manifest into a .uxml visual tree + a
// .uss stylesheet (instead of a uGUI GameObject hierarchy).
//
// UITK is a natural fit: it's top-left / +Y-down like Figma, and it does borders,
// rounded corners, opacity, clipping and rotation natively in USS. We emit one
// USS rule per element (class `fge-e<n>`) and reference sprites / baked gradient
// PNGs via background-image url() relative to the .uss file.
//
// Layout: every element is `position: absolute`. Stretched constraints emit
// left+right / top+bottom; fixed ones emit left/top + width/height (right/bottom
// pinning honoured from the manifest anchors).
// =============================================================================

using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

namespace FigForge
{
    public class UITKContext
    {
        public string outFolder = "Assets/FigForge/UI";       // where .uxml/.uss go
        public Dictionary<string, Sprite> sprites = new Dictionary<string, Sprite>();
        public System.Func<string, string, TMP_FontAssetRef> resolveFontPath; // family,style → asset path
        public System.Action<string> log = _ => { };
    }

    // tiny indirection so UxmlBuilder doesn't hard-depend on TMP types it doesn't need
    public struct TMP_FontAssetRef { public string assetPath; }

    public class UxmlResult
    {
        public string uxmlPath;
        public string ussPath;
        public string screenName;
        public int elementCount;
    }

    public static class UxmlBuilder
    {
        public static UxmlResult Build(Manifest manifest, UITKContext ctx)
        {
            var index = ManifestParser.Index(manifest);
            var roots = ManifestParser.Roots(manifest);
            string screen = Safe(manifest.screen?.name ?? "Screen");

            TextureImportHelper.EnsureFolder(ctx.outFolder);
            string ussFolderAbs = ToAbs(ctx.outFolder);
            string gradFolder = $"{ctx.outFolder}/_grad";

            var uxml = new StringBuilder();
            var uss = new StringBuilder();
            uxml.AppendLine("<ui:UXML xmlns:ui=\"UnityEngine.UIElements\" editor-extension-mode=\"False\">");

            uss.AppendLine("/* Generated by FigForge — edit freely; re-import overwrites. */");

            int counter = 0;
            float figW = manifest.screen != null && manifest.screen.figmaSize != null ? manifest.screen.figmaSize.w : 1920f;
            float figH = manifest.screen != null && manifest.screen.figmaSize != null ? manifest.screen.figmaSize.h : 1080f;

            foreach (var root in roots)
                Emit(root, index, ctx, uxml, uss, ref counter, 1, figW, figH, true, gradFolder, ussFolderAbs);

            uxml.AppendLine("</ui:UXML>");

            string uxmlPath = $"{ctx.outFolder}/{screen}.uxml";
            string ussPath = $"{ctx.outFolder}/{screen}.uss";
            File.WriteAllText(ToAbs(uxmlPath), uxml.ToString());
            File.WriteAllText(ToAbs(ussPath), uss.ToString());
            AssetDatabase.ImportAsset(uxmlPath);
            AssetDatabase.ImportAsset(ussPath);

            return new UxmlResult { uxmlPath = uxmlPath, ussPath = ussPath, screenName = manifest.screen?.name, elementCount = counter };
        }

        static void Emit(ElementData e, Dictionary<string, ElementData> index, UITKContext ctx,
            StringBuilder uxml, StringBuilder uss, ref int counter, int depth,
            float parentW, float parentH, bool isRoot, string gradFolder, string ussFolderAbs)
        {
            string cls = $"fge-e{counter++}";
            string pad = new string(' ', depth * 2);

            // ---- USS rule -----------------------------------------------------
            var rule = new StringBuilder();
            rule.Append('.').Append(cls).Append(" {\n");
            rule.Append("  position: absolute;\n");

            if (isRoot)
            {
                rule.Append($"  left: 0; top: 0; width: {Px(parentW)}; height: {Px(parentH)};\n");
            }
            else if (e.rect != null)
            {
                EmitAxis(rule, e, parentW, true);   // horizontal
                EmitAxis(rule, e, parentH, false);  // vertical
            }

            if (e.style != null)
            {
                if (e.style.opacity < 0.999f)
                    rule.Append($"  opacity: {F(e.style.opacity)};\n");
                if (e.style.cornerRadius > 0f)
                    rule.Append($"  border-radius: {Px(e.style.cornerRadius)};\n");
                EmitFill(rule, e, ctx, gradFolder, ussFolderAbs);
                if (e.style.stroke != null)
                {
                    rule.Append($"  border-width: {Px(e.style.stroke.weight)};\n");
                    rule.Append($"  border-color: {Rgba(e.style.stroke.color)};\n");
                }
            }

            // sprite background (rasterized element)
            if (!string.IsNullOrEmpty(e.asset) && ctx.sprites.ContainsKey(e.asset))
            {
                var sp = ctx.sprites[e.asset];
                var p = AssetDatabase.GetAssetPath(sp);
                if (!string.IsNullOrEmpty(p))
                    rule.Append($"  background-image: url(\"{RelUrl(ussFolderAbs, ToAbs(p))}\");\n");
            }

            if (e.clipsContent) rule.Append("  overflow: hidden;\n");
            if (Mathf.Abs(e.rotation) > 0.001f) rule.Append($"  rotate: {F(-e.rotation)}deg;\n");

            // text styling
            if (e.text != null && string.IsNullOrEmpty(e.asset))
            {
                rule.Append($"  color: {Rgba(e.text.color)};\n");
                rule.Append($"  font-size: {Px(e.text.fontSize)};\n");
                rule.Append($"  -unity-text-align: {TextAlign(e.text)};\n");
                var fr = ctx.resolveFontPath?.Invoke(e.text.fontFamily, e.text.fontStyle);
                if (fr.HasValue && !string.IsNullOrEmpty(fr.Value.assetPath))
                    rule.Append($"  -unity-font-definition: url(\"{RelUrl(ussFolderAbs, ToAbs(fr.Value.assetPath))}\");\n");
            }

            rule.Append("}\n");
            uss.Append(rule);

            // ---- UXML element -------------------------------------------------
            string classes = cls;
            if (isRoot) classes += " fge-screen";
            if (e.nav != null && !string.IsNullOrEmpty(e.nav.target))
                classes += " fge-navto-" + Safe(e.nav.target); // navigation marker (data only)
            string name = Attr(e.name ?? e.type);

            bool isCanonical = e.canonical != null;
            bool isText = e.text != null && string.IsNullOrEmpty(e.asset);

            if (isCanonical)
            {
                classes += $" fge-canonical fge-ref-{Safe(e.canonical.Ref)}";
                string label = Attr(e.canonical.label);
                string val = e.canonical.value;
                string el;
                switch (e.canonical.kind)
                {
                    case "toggle":
                        el = $"<ui:Toggle name=\"{name}\" label=\"{label}\"{(val == "true" ? " value=\"true\"" : "")} class=\"{classes}\" />";
                        break;
                    case "input":
                        el = $"<ui:TextField name=\"{name}\" label=\"{label}\" value=\"{Attr(val)}\" class=\"{classes}\" />";
                        break;
                    case "dropdown":
                        el = $"<ui:DropdownField name=\"{name}\" label=\"{label}\" class=\"{classes}\" />"; // choices set in code
                        break;
                    case "slider":
                        el = $"<ui:Slider name=\"{name}\" label=\"{label}\" low-value=\"0\" high-value=\"100\"{(float.TryParse(val, out var sv) ? $" value=\"{F(sv)}\"" : "")} class=\"{classes}\" />";
                        break;
                    default:
                        el = $"<ui:Button name=\"{name}\" text=\"{label}\" class=\"{classes}\" />";
                        break;
                }
                uxml.Append(pad).Append(el).Append('\n');
                return; // canonical controls have no imported children
            }
            if (isText)
            {
                uxml.Append(pad).Append($"<ui:Label name=\"{name}\" text=\"{Attr(e.text.content)}\" class=\"{classes}\" />\n");
                return;
            }

            // container / image
            var kids = new List<ElementData>();
            if (e.children != null)
                foreach (var id in e.children)
                    if (index.TryGetValue(id, out var c)) kids.Add(c);

            if (kids.Count == 0)
            {
                uxml.Append(pad).Append($"<ui:VisualElement name=\"{name}\" class=\"{classes}\" />\n");
            }
            else
            {
                uxml.Append(pad).Append($"<ui:VisualElement name=\"{name}\" class=\"{classes}\">\n");
                foreach (var c in kids)
                    Emit(c, index, ctx, uxml, uss, ref counter, depth + 1,
                        e.rect != null ? e.rect.w : parentW, e.rect != null ? e.rect.h : parentH,
                        false, gradFolder, ussFolderAbs);
                uxml.Append(pad).Append("</ui:VisualElement>\n");
            }
        }

        // Per-axis position: stretch → both edges; else edge + size, honouring pin.
        static void EmitAxis(StringBuilder rule, ElementData e, float parentDim, bool horizontal)
        {
            var t = e.transform;
            float x = horizontal ? e.rect.x : e.rect.y;
            float size = horizontal ? e.rect.w : e.rect.h;
            float aMin = t != null ? (horizontal ? t.anchorMin[0] : t.anchorMin[1]) : 0f;
            float aMax = t != null ? (horizontal ? t.anchorMax[0] : t.anchorMax[1]) : 0f;
            float farEdge = parentDim - (x + size);

            string startProp = horizontal ? "left" : "top";
            // NB: manifest vertical anchors are y-up (1 = Figma top). UITK is y-down,
            // so anchor 1 == top edge == the `top` side. The mapping lines up.
            string endProp = horizontal ? "right" : "bottom";
            string sizeProp = horizontal ? "width" : "height";

            bool stretch = Mathf.Abs(aMin - aMax) > 0.001f;
            if (stretch)
            {
                rule.Append($"  {startProp}: {Px(x)}; {endProp}: {Px(farEdge)};\n");
            }
            else if (aMin >= 0.999f) // pinned to the "max" anchor → far edge
            {
                rule.Append($"  {endProp}: {Px(farEdge)}; {sizeProp}: {Px(size)};\n");
            }
            else // start-pinned or centred (approximate centre with start offset)
            {
                rule.Append($"  {startProp}: {Px(x)}; {sizeProp}: {Px(size)};\n");
            }
        }

        static void EmitFill(StringBuilder rule, ElementData e, UITKContext ctx, string gradFolder, string ussFolderAbs)
        {
            var fill = e.style.fill;
            if (fill == null) return;
            if (fill.kind == "solid" && fill.color != null)
            {
                rule.Append($"  background-color: {Rgba(fill.color)};\n");
            }
            else if (fill.kind == "gradient")
            {
                var png = BakeGradientPng(fill, gradFolder);
                if (!string.IsNullOrEmpty(png))
                    rule.Append($"  background-image: url(\"{RelUrl(ussFolderAbs, ToAbs(png))}\");\n");
            }
        }

        // ---- gradient → PNG (UITK has no CSS gradients) -----------------------
        static string BakeGradientPng(Fill fill, string folder)
        {
            if (fill.stops == null || fill.stops.Count == 0) return null;
            TextureImportHelper.EnsureFolder(folder);
            string key = GradKey(fill);
            string path = $"{folder}/grad_{key}.png";
            if (File.Exists(ToAbs(path))) return path;

            const int res = 128;
            bool radial = fill.gradient == "radial" || fill.gradient == "diamond";
            var tex = new Texture2D(res, res, TextureFormat.RGBA32, false);
            float cx = (res - 1) * 0.5f, cy = (res - 1) * 0.5f, maxR = Mathf.Sqrt(cx * cx + cy * cy);
            var px = new Color32[res * res];
            for (int y = 0; y < res; y++)
                for (int x = 0; x < res; x++)
                {
                    float tt = radial
                        ? Mathf.Clamp01(Mathf.Sqrt((x - cx) * (x - cx) + (y - cy) * (y - cy)) / maxR)
                        : (float)x / (res - 1);
                    px[y * res + x] = SampleStops(fill.stops, tt);
                }
            tex.SetPixels32(px);
            tex.Apply();
            File.WriteAllBytes(ToAbs(path), tex.EncodeToPNG());
            Object.DestroyImmediate(tex);
            AssetDatabase.ImportAsset(path);
            return path;
        }

        static Color SampleStops(List<GradientStop> stops, float t)
        {
            GradientStop a = stops[0], b = stops[stops.Count - 1];
            for (int i = 0; i < stops.Count - 1; i++)
                if (t >= stops[i].position && t <= stops[i + 1].position) { a = stops[i]; b = stops[i + 1]; break; }
            float span = Mathf.Max(0.0001f, b.position - a.position);
            return Color.Lerp(Col(a.color), Col(b.color), Mathf.Clamp01((t - a.position) / span));
        }

        // ---- helpers ----------------------------------------------------------
        static string GradKey(Fill f)
        {
            var sb = new StringBuilder(f.gradient ?? "linear");
            foreach (var s in f.stops)
            {
                sb.Append('_').Append(Mathf.RoundToInt(s.position * 100));
                if (s.color != null) foreach (var c in s.color) sb.Append(Mathf.RoundToInt(c * 255)).Append('x');
            }
            return sb.ToString();
        }

        static string TextAlign(TextData t)
        {
            string v = t.alignV == "middle" ? "middle" : t.alignV == "bottom" ? "lower" : "upper";
            string h = t.alignH == "center" ? "center" : t.alignH == "right" ? "right" : "left";
            return $"{v}-{h}";
        }

        static string Px(float v) => Mathf.RoundToInt(v).ToString(CultureInfo.InvariantCulture) + "px";
        static string F(float v) => v.ToString("0.###", CultureInfo.InvariantCulture);
        static Color Col(float[] c) => c != null && c.Length >= 4 ? new Color(c[0], c[1], c[2], c[3]) : Color.white;
        static string Rgba(float[] c)
        {
            if (c == null || c.Length < 4) return "rgba(255, 255, 255, 1)";
            return $"rgba({Mathf.RoundToInt(c[0] * 255)}, {Mathf.RoundToInt(c[1] * 255)}, {Mathf.RoundToInt(c[2] * 255)}, {F(c[3])})";
        }
        static string Safe(string s)
        {
            var sb = new StringBuilder();
            foreach (var ch in s ?? "x") sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
            var r = sb.ToString().Trim('_');
            return r.Length > 0 ? r : "x";
        }
        static string Attr(string s) => (s ?? "")
            .Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;").Replace("\n", " ");

        static string ToAbs(string assetsPath)
        {
            string root = Directory.GetParent(Application.dataPath).FullName;
            return Path.Combine(root, assetsPath.Replace('/', Path.DirectorySeparatorChar));
        }
        // relative URL from the .uss folder to a target asset, forward-slashed.
        static string RelUrl(string fromFolderAbs, string toAbs)
        {
            var fromUri = new System.Uri(fromFolderAbs.TrimEnd('/', '\\') + "/");
            var toUri = new System.Uri(toAbs);
            return System.Uri.UnescapeDataString(fromUri.MakeRelativeUri(toUri).ToString());
        }
    }
}
