// =============================================================================
// FigForge — frame code generator. Emits the strongly-typed accessor layer:
//   • <Frame>.g.cs   — `public partial class LaunchPage : FigForgeFrame` with a
//                      [SerializeField] ref + typed property per frame-scoped element.
//   • FrameManager.g.cs — static accessors (FrameManager.LaunchPage), grouped by
//                      section as nested static classes.
//   • deterministic .cs.meta GUIDs so the generated prefab YAML can reference the
//     frame script BEFORE it compiles (one-pass import, no domain-reload wiring).
//
// This file is PURE generation (string in → string out) + the element→C# type map.
// The importer assembles the FrameModel from the manifest and writes the files +
// wires the [SerializeField] refs by fileID when it authors the frame prefab YAML.
// =============================================================================

using System;
using System.Collections.Generic;
using System.Text;

namespace FigForge
{
    /// <summary>One typed member of a generated frame: a child element surfaced as a
    /// serialized, strongly-typed accessor.</summary>
    internal struct FrameMember
    {
        public string identifier;  // case-preserved C# identifier, e.g. "button_default"
        public string csharpType;  // fully-qualified, e.g. "FigForge.FigForgeButton"
        public string sourceName;  // the child object/component name to wire in the prefab YAML

        /// <summary>The backing serialized field name (the property is `identifier`). A
        /// keyword identifier like `@class` keeps a clean field `_class`.</summary>
        public string FieldName => "_" + (identifier ?? "").TrimStart('@');
    }

    /// <summary>One generated frame.</summary>
    internal struct FrameModel
    {
        public string className;   // case-preserved, e.g. "LaunchPage"
        public string screenKey;   // runtime FigForgeFrame.screenName (the Find() key)
        public string section;     // enclosing section identifier, "" if none
        public string scriptGuid;  // deterministic 32-hex GUID for the generated .cs
        public List<FrameMember> members;
    }

    internal static class FrameCodeGen
    {
        public const string GeneratedNamespace = "FigForge.Generated";

        // ---- deterministic GUID (so prefab YAML can name the script pre-compile) -----
        public static string DeterministicGuid(string seed)
        {
            ulong h1 = Fnv("figforge-frame-" + seed);
            ulong h2 = Fnv(seed + "-frame-figforge");
            return h1.ToString("x16") + h2.ToString("x16"); // 32 hex chars
        }

        static ulong Fnv(string s)
        {
            unchecked
            {
                ulong h = 14695981039346656037UL;
                for (int i = 0; i < s.Length; i++) { h ^= s[i]; h *= 1099511628211UL; }
                return h;
            }
        }

        // ---- <Frame>.g.cs -------------------------------------------------------------
        public static string EmitFrameClass(FrameModel f)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> FigForge frame accessors — regenerated on import. Do not edit.");
            sb.AppendLine("// Add behaviour in a SEPARATE file: `public partial class " + f.className + " { ... }`.");
            sb.AppendLine("using TMPro;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine();
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public partial class " + f.className + " : FigForge.FigForgeFrame");
            sb.AppendLine("    {");
            if (f.members != null)
            {
                foreach (var m in f.members)
                {
                    sb.AppendLine("        [SerializeField] " + m.csharpType + " " + m.FieldName + ";");
                    sb.AppendLine("        public " + m.csharpType + " " + m.identifier + " => " + m.FieldName + ";");
                }
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ---- FrameManager.g.cs --------------------------------------------------------
        public static string EmitFrameManager(IList<FrameModel> frames)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> FigForge static frame accessors — regenerated on import. Do not edit.");
            sb.AppendLine("using FigForge.Generated;");
            sb.AppendLine();
            sb.AppendLine("namespace FigForge");
            sb.AppendLine("{");
            sb.AppendLine("    public partial class FrameManager");
            sb.AppendLine("    {");

            foreach (var f in frames)
                if (string.IsNullOrEmpty(f.section))
                    sb.AppendLine("        " + Accessor(f));

            var sections = new SortedSet<string>(StringComparer.Ordinal);
            foreach (var f in frames) if (!string.IsNullOrEmpty(f.section)) sections.Add(f.section);
            foreach (var sec in sections)
            {
                sb.AppendLine();
                sb.AppendLine("        public static class " + sec);
                sb.AppendLine("        {");
                foreach (var f in frames)
                    if (f.section == sec)
                        sb.AppendLine("            " + Accessor(f));
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        static string Accessor(FrameModel f)
        {
            string t = GeneratedNamespace + "." + f.className;
            return "public static " + t + " " + f.className
                 + " => Active != null ? Active.Find(\"" + Escape(f.screenKey) + "\") as " + t + " : null;";
        }

        // ---- generated .cs.meta + asmdef ----------------------------------------------
        public static string EmitScriptMeta(string guid)
        {
            return "fileFormatVersion: 2\n"
                 + "guid: " + guid + "\n"
                 + "MonoImporter:\n"
                 + "  externalObjects: {}\n"
                 + "  serializedVersion: 2\n"
                 + "  defaultReferences: []\n"
                 + "  executionOrder: 0\n"
                 + "  icon: {instanceID: 0}\n"
                 + "  userData: \n"
                 + "  assetBundleName: \n"
                 + "  assetBundleVariant: \n";
        }

        public static string EmitAsmdef()
        {
            return "{\n"
                 + "  \"name\": \"FigForge.Generated\",\n"
                 + "  \"rootNamespace\": \"FigForge.Generated\",\n"
                 + "  \"references\": [\n"
                 + "    \"FigForge.Runtime\",\n"
                 + "    \"Unity.TextMeshPro\",\n"
                 + "    \"UnityEngine.UI\"\n"
                 + "  ],\n"
                 + "  \"autoReferenced\": true\n"
                 + "}\n";
        }

        // ---- element → C# accessor type ----------------------------------------------
        public static string CSharpType(ElementData e)
        {
            var c = e != null ? e.canonical : null;
            if (c != null && !string.IsNullOrEmpty(c.kind))
            {
                switch (c.kind)
                {
                    case "button": return "FigForge.FigForgeButton";
                    case "toggle":
                    case "radio": return "FigForge.FigForgeToggle";
                    case "dropdown": return "FigForge.FigForgeDropdown";
                    case "input": return "FigForge.FigForgeInputField";
                    case "list": return "FigForge.FigForgeList";
                }
            }
            if (e != null && (e.type == "TEXT" || (e.components != null && e.components.Contains("TextMeshProUGUI"))))
                return "TMPro.TMP_Text";
            if (e != null && e.components != null && e.components.Contains("Image"))
                return "UnityEngine.UI.Image";
            return "UnityEngine.RectTransform"; // plain container / unknown
        }

        static string Escape(string s) => (s ?? "").Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
