// =============================================================================
// FigForge — frame code generator. Emits the strongly-typed accessor layer:
//   • <Frame>.g.cs   — `public partial class LaunchPage : FigForgeFrame` with a
//                      [SerializeField] ref + typed property per frame-scoped element.
//   • FrameManager.g.cs — static accessors (FrameManager.LaunchPage), grouped by
//                      section as nested static classes.
//   • deterministic .cs.meta GUIDs so the generated prefab YAML can reference the
//     frame script BEFORE it compiles (one-pass import, no domain-reload wiring).
//
// This file is PURE generation (string in → string out) + the element→C# type map.
// The importer assembles the FrameModel from the manifest and writes the files +
// wires the [SerializeField] refs by fileID when it authors the frame prefab YAML.
// =============================================================================

using System;
using System.Collections.Generic;
using System.Text;

namespace FigForge
{
    /// <summary>One typed member of a generated frame: a child element surfaced as a
    /// serialized, strongly-typed accessor.</summary>
    internal struct FrameMember
    {
        public string identifier;  // case-preserved C# identifier, e.g. "button_default"
        public string csharpType;  // fully-qualified, e.g. "FigForge.FigForgeButton"
        public string sourceName;  // manifest element id used to wire the generated field
        public string sourceType;  // manifest element type, e.g. GROUP or FRAME
        public string parentId;    // manifest parent id, used for generated container scopes
        public string scopeParentId;
        public bool exposeOnFrame;
        public bool isGroup;
        public string groupTypeName;

        /// <summary>Registry key + serialized-field stem. The property keeps any `@` escape,
        /// but the string key and backing field drop it: `@class` → key "class", field "_class".</summary>
        public string Key => (identifier ?? "").TrimStart('@');
        public string FieldName => "_" + Key;
    }

    /// <summary>One generated frame.</summary>
    internal struct FrameModel
    {
        public string className;   // case-preserved, e.g. "LaunchPage"
        public string screenKey;   // runtime FrameManager.Find key (object name or sanitized object name)
        public string section;     // enclosing section identifier, "" if none
        public string scriptGuid;  // deterministic 32-hex GUID for the generated .cs
        public List<FrameMember> members;
    }

    internal static class FrameCodeGen
    {
        public const string GeneratedNamespace = "FigForge.Generated";

        // ---- deterministic GUID (so prefab YAML can name the script pre-compile) -----
        public static string DeterministicGuid(string seed)
        {
            ulong h1 = Fnv("figforge-frame-" + seed);
            ulong h2 = Fnv(seed + "-frame-figforge");
            return h1.ToString("x16") + h2.ToString("x16"); // 32 hex chars
        }

        static ulong Fnv(string s)
        {
            unchecked
            {
                ulong h = 14695981039346656037UL;
                for (int i = 0; i < s.Length; i++) { h ^= s[i]; h *= 1099511628211UL; }
                return h;
            }
        }

        // ---- <Frame>.g.cs -------------------------------------------------------------
        public static string EmitFrameClass(FrameModel f)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> FigForge frame accessors — regenerated on import. Do not edit.");
            sb.AppendLine("// Add behaviour in a SEPARATE file: `public partial class " + f.className + " { ... }`.");
            sb.AppendLine("// Show/hide any accessor from code: FigForge controls have an `IsVisible` property;");
            sb.AppendLine("// every element (Image/TMP/RectTransform too) has SetVisible(bool)/GetVisible()");
            sb.AppendLine("// extensions (using FigForge;). Both drive GameObject.SetActive.");
            sb.AppendLine("// Add click listeners in `public override void OnBind()` for hidden-at-start frames.");
            sb.AppendLine("using TMPro;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine();
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public partial class " + f.className + " : FigForge.FigForgeFrame");
            sb.AppendLine("    {");
            if (f.members != null)
            {
                foreach (var m in f.members)
                {
                    sb.AppendLine("        [SerializeField] " + m.csharpType + " " + m.FieldName + ";");
                    if (m.isGroup)
                        sb.AppendLine("        " + m.groupTypeName + " " + m.FieldName + "Scope;");
                    if (m.exposeOnFrame)
                        sb.AppendLine("        public " + PublicType(m) + " " + m.identifier + " => " + AccessExpr("", m) + ";");
                }
            }
            if (f.members != null)
            {
                foreach (var group in f.members)
                {
                    if (!group.isGroup) continue;
                    sb.AppendLine();
                    sb.AppendLine("        public sealed class " + group.groupTypeName);
                    sb.AppendLine("        {");
                    sb.AppendLine("            readonly " + f.className + " _frame;");
                    sb.AppendLine("            internal " + group.groupTypeName + "(" + f.className + " frame) { _frame = frame; }");
                    sb.AppendLine("            public FigForge.FigForgeFrameElement Element => _frame.__Get(ref _frame." + group.FieldName + ", \"" + Escape(group.Key) + "\");");
                    sb.AppendLine("            public RectTransform __rectTransform => Element != null ? Element.RectTransform : null;");
                    sb.AppendLine("            public RectTransform RectTransform => __rectTransform;");
                    sb.AppendLine("            public GameObject GameObject => Element != null ? Element.GameObject : null;");
                    sb.AppendLine("            public bool IsVisible { get => Element != null && Element.IsVisible; set => SetVisible(value); }");
                    sb.AppendLine("            public void SetVisible(bool visible) { if (Element != null) Element.SetVisible(visible); }");
                    sb.AppendLine("            public bool GetVisible() => Element != null && Element.GetVisible();");
                    foreach (var child in f.members)
                    {
                        if (child.scopeParentId != group.sourceName) continue;
                        sb.AppendLine("            public " + PublicType(child) + " " + child.identifier + " => " + AccessExpr("_frame.", child) + ";");
                    }
                    sb.AppendLine("        }");
                }
            }
            sb.AppendLine();
            sb.AppendLine("        // The importer's post-compile hook calls this to fill the [SerializeField]");
            sb.AppendLine("        // refs from the frame's element registry (keyed by the same identifiers).");
            sb.AppendLine("        public override void __WireFrame(FigForge.FigForgeScreen reg)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (reg == null) return;");
            if (f.members != null)
                foreach (var m in f.members)
                    sb.AppendLine("            " + m.FieldName + " = reg.Get<" + m.csharpType + ">(\"" + m.Key + "\");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        static string PublicType(FrameMember m) => m.isGroup ? m.groupTypeName : m.csharpType;

        static string AccessExpr(string frame, FrameMember m)
        {
            if (!m.isGroup) return frame + "__Get(ref " + frame + m.FieldName + ", \"" + Escape(m.Key) + "\")";
            var owner = string.IsNullOrEmpty(frame) ? "this" : frame.TrimEnd('.');
            return frame + m.FieldName + "Scope ?? (" + frame + m.FieldName + "Scope = new " + m.groupTypeName + "(" + owner + "))";
        }

        // ---- FrameManager.g.cs --------------------------------------------------------
        public static string EmitFrameManager(IList<FrameModel> frames)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> FigForge static frame accessors — regenerated on import. Do not edit.");
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class Frames");
            sb.AppendLine("    {");

            foreach (var f in frames)
                if (string.IsNullOrEmpty(f.section))
                    sb.AppendLine("        " + Accessor(f));

            var sections = new SortedSet<string>(StringComparer.Ordinal);
            foreach (var f in frames) if (!string.IsNullOrEmpty(f.section)) sections.Add(f.section);
            foreach (var sec in sections)
            {
                sb.AppendLine();
                sb.AppendLine("        public static partial class " + sec);
                sb.AppendLine("        {");
                foreach (var f in frames)
                    if (f.section == sec)
                        sb.AppendLine("            " + Accessor(f));
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // A single-frame `Frames` partial — one file per frame so page-by-page imports
        // don't clobber each other's accessors. Sections become a partial nested static
        // class (multiple frames in a section each contribute to it).
        public static string EmitFrameManagerForFrame(FrameModel f)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> FigForge frame accessor — regenerated on import. Do not edit.");
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class Frames");
            sb.AppendLine("    {");
            if (string.IsNullOrEmpty(f.section))
            {
                sb.AppendLine("        " + Accessor(f));
            }
            else
            {
                sb.AppendLine("        public static partial class " + f.section);
                sb.AppendLine("        {");
                sb.AppendLine("            " + Accessor(f));
                sb.AppendLine("        }");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // The fixed `Frames` core — navigation that proxies the internal FrameManager.
        // Written once (Frames.Core.g.cs); per-frame files add the typed accessors.
        public static string EmitFramesCore()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> FigForge frame navigation — regenerated on import. Do not edit.");
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    // The single public entry point. Wraps the internal FrameManager engine.");
            sb.AppendLine("    public static partial class Frames");
            sb.AppendLine("    {");
            sb.AppendLine("        // The frame currently shown (null before any Show / in edit mode).");
            sb.AppendLine("        public static FigForge.FigForgeFrame Current");
            sb.AppendLine("            => FigForge.FrameManager.Resolve()?.Current;");
            sb.AppendLine();
            sb.AppendLine("        // Typed + null-safe navigation: Frames.Show(Frames.Settings). (Or Frames.Settings.Show().)");
            sb.AppendLine("        public static void Show(FigForge.FigForgeFrame frame) { if (frame != null) frame.Show(); }");
            sb.AppendLine();
            sb.AppendLine("        // Ensure every registered frame has run OnBind(), including inactive pages.");
            sb.AppendLine("        public static void BindAll() { FigForge.FrameManager.Resolve()?.BindAll(); }");
            sb.AppendLine();
            sb.AppendLine("        // Run an action after a delay, chainable: Frames.After(1f, A).After(2f, B).");
            sb.AppendLine("        public static DelayChain After(float seconds, System.Action action)");
            sb.AppendLine("            => new DelayChain(FigForge.FrameManager.Resolve()).After(seconds, action);");
            sb.AppendLine();
            sb.AppendLine("        public sealed class DelayChain");
            sb.AppendLine("        {");
            sb.AppendLine("            struct Step");
            sb.AppendLine("            {");
            sb.AppendLine("                public float seconds;");
            sb.AppendLine("                public System.Action action;");
            sb.AppendLine("                public Step(float seconds, System.Action action) { this.seconds = seconds; this.action = action; }");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            readonly FigForge.FrameManager _manager;");
            sb.AppendLine("            readonly System.Collections.Generic.Queue<Step> _steps = new System.Collections.Generic.Queue<Step>();");
            sb.AppendLine("            UnityEngine.Coroutine _coroutine;");
            sb.AppendLine();
            sb.AppendLine("            internal DelayChain(FigForge.FrameManager manager) { _manager = manager; }");
            sb.AppendLine("            public bool IsRunning => _coroutine != null;");
            sb.AppendLine();
            sb.AppendLine("            public DelayChain After(float seconds, System.Action action)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (action == null) return this;");
            sb.AppendLine("                _steps.Enqueue(new Step(seconds, action));");
            sb.AppendLine("                if (_manager != null && _coroutine == null)");
            sb.AppendLine("                    _coroutine = _manager.StartCoroutine(Run());");
            sb.AppendLine("                return this;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            public void Cancel()");
            sb.AppendLine("            {");
            sb.AppendLine("                _steps.Clear();");
            sb.AppendLine("                if (_manager != null && _coroutine != null)");
            sb.AppendLine("                    _manager.StopCoroutine(_coroutine);");
            sb.AppendLine("                _coroutine = null;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            System.Collections.IEnumerator Run()");
            sb.AppendLine("            {");
            sb.AppendLine("                while (_steps.Count > 0)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var step = _steps.Dequeue();");
            sb.AppendLine("                    if (step.seconds > 0f) yield return new UnityEngine.WaitForSeconds(step.seconds);");
            sb.AppendLine("                    try { step.action(); }");
            sb.AppendLine("                    catch (System.Exception e) { UnityEngine.Debug.LogException(e); }");
            sb.AppendLine("                }");
            sb.AppendLine("                _coroutine = null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        static string Accessor(FrameModel f)
        {
            // Emitted INSIDE namespace FigForge.Generated, so the frame type is unqualified;
            // the manager is the package's FigForge.FrameManager (cross-assembly reference).
            return "public static " + f.className + " " + f.className
                 + " => FigForge.FrameManager.Resolve()?.Find(\"" + Escape(f.screenKey) + "\") as " + f.className + ";";
        }

        // ---- generated .cs.meta + asmdef ----------------------------------------------
        public static string EmitScriptMeta(string guid)
        {
            return "fileFormatVersion: 2\n"
                 + "guid: " + guid + "\n"
                 + "MonoImporter:\n"
                 + "  externalObjects: {}\n"
                 + "  serializedVersion: 2\n"
                 + "  defaultReferences: []\n"
                 + "  executionOrder: 0\n"
                 + "  icon: {instanceID: 0}\n"
                 + "  userData: \n"
                 + "  assetBundleName: \n"
                 + "  assetBundleVariant: \n";
        }

        public static string EmitAsmdef()
        {
            return "{\n"
                 + "  \"name\": \"FigForge.Generated\",\n"
                 + "  \"rootNamespace\": \"FigForge.Generated\",\n"
                 + "  \"references\": [\n"
                 + "    \"FigForge.Runtime\",\n"
                 + "    \"Unity.TextMeshPro\",\n"
                 + "    \"UnityEngine.UI\"\n"
                 + "  ],\n"
                 + "  \"autoReferenced\": true\n"
                 + "}\n";
        }

        // ---- element → C# accessor type ----------------------------------------------
        public static string CSharpType(ElementData e)
        {
            var c = e != null ? e.canonical : null;
            if (c != null && !string.IsNullOrEmpty(c.kind))
            {
                switch (c.kind)
                {
                    case "button": return "FigForge.FigForgeButton";
                    case "toggle":
                    case "radio": return "FigForge.FigForgeToggle";
                    case "switch": return "FigForge.FigForgeSwitch";
                    case "dropdown": return "FigForge.FigForgeDropdown";
                    case "input": return "FigForge.FigForgeInputField";
                    case "stepper": return "FigForge.FigForgeStepper";
                    case "slider": return "FigForge.FigForgeSlider";
                    case "progress": return "FigForge.FigForgeProgress";
                    case "list": return "FigForge.FigForgeList";
                    case "table": return "FigForge.FigForgeTable";
                }
            }
            if (e != null && (e.type == "TEXT" || (e.components != null && e.components.Contains("TextMeshProUGUI"))))
                return "TMPro.TMP_Text";
            if (e != null && e.components != null && e.components.Contains("Image"))
                return "UnityEngine.UI.Image";
            return "UnityEngine.RectTransform"; // plain container / unknown
        }

        static string Escape(string s) => (s ?? "").Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
